no-permission: "&cYou do not have permission!"

#COORDS
coords:
 - '&7&m&l---------------------------------------------'
 - '&6&lCoords'
 
cobble-enabled:
 - '&7&m&l---------------------------------------------'
 - '&4&lCobble &cenabled!'
 - '&7&m&l---------------------------------------------'
 
cobble-disabled:
 - '&7&m&l---------------------------------------------'
 - '&4&lCobble &cdisabled!'
 - '&7&m&l---------------------------------------------'
 
teamspeak:
 - '&7&m&l---------------------------------------------'
 - '&4&lTeamspeakthing'
 - '&7&m&l---------------------------------------------'
 
vanish-enabled:
 - '&7&m&l---------------------------------------------'
 - '&6&lVanish &cenabled!'
 - '&7&m&l---------------------------------------------'
 
vanish-disabled:
 - '&7&m&l---------------------------------------------'
 - '&6&lVanish &cdisabled!'
 - '&7&m&l---------------------------------------------'
 
blacklists: 
 - '231.1234.2314'